---
name: all_url_check

'on':
  workflow_dispatch:
  push:
  schedule:
    - cron: '25 */3 * * *'

jobs:
  run_lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: link_check with lychee-action
        id: link_check
        uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2.7.0
        with:
          args: --verbose --insecure --no-progress **/*.tex **/*.md
          fail: true
...
