---
name: all_url_check

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '25 */3 * * *'

jobs:
  run_lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4

      - name: link_check with lychee-action
        id: link_check
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: --verbose --insecure --no-progress **/*.tex **/*.md
          fail: true
...
