---
name: latex_linter_check

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'

jobs:
  run_chktex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac  # v4

      - name: LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2
...
