---
name: latex_linter_check

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'

jobs:
  run_chktex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2
...
