---
name: latex_linter_check

'on':
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'

jobs:
  run_chktex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4

      - name: LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2
...
