---
name: latex_linter_check

'on':
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'

jobs:
  run_chktex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633  # v4

      - name: LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2
...
